// Generated by gencpp from file human_detection_pipeline/HumanTrackingData.msg
// DO NOT EDIT!


#ifndef HUMAN_DETECTION_PIPELINE_MESSAGE_HUMANTRACKINGDATA_H
#define HUMAN_DETECTION_PIPELINE_MESSAGE_HUMANTRACKINGDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace human_detection_pipeline
{
template <class ContainerAllocator>
struct HumanTrackingData_
{
  typedef HumanTrackingData_<ContainerAllocator> Type;

  HumanTrackingData_()
    : position()
    , tracking_id(0)
    , distance(0.0)
    , confidence(0.0)  {
    }
  HumanTrackingData_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , tracking_id(0)
    , distance(0.0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef int32_t _tracking_id_type;
  _tracking_id_type tracking_id;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> const> ConstPtr;

}; // struct HumanTrackingData_

typedef ::human_detection_pipeline::HumanTrackingData_<std::allocator<void> > HumanTrackingData;

typedef boost::shared_ptr< ::human_detection_pipeline::HumanTrackingData > HumanTrackingDataPtr;
typedef boost::shared_ptr< ::human_detection_pipeline::HumanTrackingData const> HumanTrackingDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator1> & lhs, const ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.tracking_id == rhs.tracking_id &&
    lhs.distance == rhs.distance &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator1> & lhs, const ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace human_detection_pipeline

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc13d57981a0f76b7a28dbe20a53f4bb";
  }

  static const char* value(const ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc13d57981a0f76bULL;
  static const uint64_t static_value2 = 0x7a28dbe20a53f4bbULL;
};

template<class ContainerAllocator>
struct DataType< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_detection_pipeline/HumanTrackingData";
  }

  static const char* value(const ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Define a message for storing the position (x, y, z)\n"
"geometry_msgs/Point position   # A standard ROS message type for a 3D point (x, y, z)\n"
"\n"
"# Tracking information for one human\n"
"int32 tracking_id               # Unique identifier for the human\n"
"float32 distance                # Distance to the human\n"
"float32 confidence              # Confidence of the tracking data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.tracking_id);
      stream.next(m.distance);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanTrackingData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "tracking_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tracking_id);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_DETECTION_PIPELINE_MESSAGE_HUMANTRACKINGDATA_H
