// Generated by gencpp from file human_detection_pipeline/HumansList.msg
// DO NOT EDIT!


#ifndef HUMAN_DETECTION_PIPELINE_MESSAGE_HUMANSLIST_H
#define HUMAN_DETECTION_PIPELINE_MESSAGE_HUMANSLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <human_detection_pipeline/HumanTrackingData.h>

namespace human_detection_pipeline
{
template <class ContainerAllocator>
struct HumansList_
{
  typedef HumansList_<ContainerAllocator> Type;

  HumansList_()
    : humans()  {
    }
  HumansList_(const ContainerAllocator& _alloc)
    : humans(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >> _humans_type;
  _humans_type humans;





  typedef boost::shared_ptr< ::human_detection_pipeline::HumansList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_detection_pipeline::HumansList_<ContainerAllocator> const> ConstPtr;

}; // struct HumansList_

typedef ::human_detection_pipeline::HumansList_<std::allocator<void> > HumansList;

typedef boost::shared_ptr< ::human_detection_pipeline::HumansList > HumansListPtr;
typedef boost::shared_ptr< ::human_detection_pipeline::HumansList const> HumansListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_detection_pipeline::HumansList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_detection_pipeline::HumansList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::human_detection_pipeline::HumansList_<ContainerAllocator1> & lhs, const ::human_detection_pipeline::HumansList_<ContainerAllocator2> & rhs)
{
  return lhs.humans == rhs.humans;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::human_detection_pipeline::HumansList_<ContainerAllocator1> & lhs, const ::human_detection_pipeline::HumansList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace human_detection_pipeline

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::human_detection_pipeline::HumansList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_detection_pipeline::HumansList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_detection_pipeline::HumansList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_detection_pipeline::HumansList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_detection_pipeline::HumansList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_detection_pipeline::HumansList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_detection_pipeline::HumansList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7644a1a2834d6a42a244e016b847ece";
  }

  static const char* value(const ::human_detection_pipeline::HumansList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7644a1a2834d6a4ULL;
  static const uint64_t static_value2 = 0x2a244e016b847eceULL;
};

template<class ContainerAllocator>
struct DataType< ::human_detection_pipeline::HumansList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_detection_pipeline/HumansList";
  }

  static const char* value(const ::human_detection_pipeline::HumansList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_detection_pipeline::HumansList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# List of human tracking data\n"
"HumanTrackingData[] humans\n"
"\n"
"================================================================================\n"
"MSG: human_detection_pipeline/HumanTrackingData\n"
"# Define a message for storing the position (x, y, z)\n"
"geometry_msgs/Point position   # A standard ROS message type for a 3D point (x, y, z)\n"
"\n"
"# Tracking information for one human\n"
"int32 tracking_id               # Unique identifier for the human\n"
"float32 distance                # Distance to the human\n"
"float32 confidence              # Confidence of the tracking data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::human_detection_pipeline::HumansList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_detection_pipeline::HumansList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.humans);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumansList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_detection_pipeline::HumansList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_detection_pipeline::HumansList_<ContainerAllocator>& v)
  {
    s << indent << "humans[]" << std::endl;
    for (size_t i = 0; i < v.humans.size(); ++i)
    {
      s << indent << "  humans[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::human_detection_pipeline::HumanTrackingData_<ContainerAllocator> >::stream(s, indent + "    ", v.humans[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_DETECTION_PIPELINE_MESSAGE_HUMANSLIST_H
