# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from human_detection_pipeline/HumanTrackingData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class HumanTrackingData(genpy.Message):
  _md5sum = "dc13d57981a0f76b7a28dbe20a53f4bb"
  _type = "human_detection_pipeline/HumanTrackingData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Define a message for storing the position (x, y, z)
geometry_msgs/Point position   # A standard ROS message type for a 3D point (x, y, z)

# Tracking information for one human
int32 tracking_id               # Unique identifier for the human
float32 distance                # Distance to the human
float32 confidence              # Confidence of the tracking data

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['position','tracking_id','distance','confidence']
  _slot_types = ['geometry_msgs/Point','int32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,tracking_id,distance,confidence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HumanTrackingData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.tracking_id is None:
        self.tracking_id = 0
      if self.distance is None:
        self.distance = 0.
      if self.confidence is None:
        self.confidence = 0.
    else:
      self.position = geometry_msgs.msg.Point()
      self.tracking_id = 0
      self.distance = 0.
      self.confidence = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3di2f().pack(_x.position.x, _x.position.y, _x.position.z, _x.tracking_id, _x.distance, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.position.x, _x.position.y, _x.position.z, _x.tracking_id, _x.distance, _x.confidence,) = _get_struct_3di2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3di2f().pack(_x.position.x, _x.position.y, _x.position.z, _x.tracking_id, _x.distance, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.position.x, _x.position.y, _x.position.z, _x.tracking_id, _x.distance, _x.confidence,) = _get_struct_3di2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3di2f = None
def _get_struct_3di2f():
    global _struct_3di2f
    if _struct_3di2f is None:
        _struct_3di2f = struct.Struct("<3di2f")
    return _struct_3di2f
