// Generated by gencpp from file human_clustering_pipeline/OptimalPosition.msg
// DO NOT EDIT!


#ifndef HUMAN_CLUSTERING_PIPELINE_MESSAGE_OPTIMALPOSITION_H
#define HUMAN_CLUSTERING_PIPELINE_MESSAGE_OPTIMALPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace human_clustering_pipeline
{
template <class ContainerAllocator>
struct OptimalPosition_
{
  typedef OptimalPosition_<ContainerAllocator> Type;

  OptimalPosition_()
    : x(0.0)
    , y(0.0)
    , orientation(0.0)
    , priority_score(0.0)  {
    }
  OptimalPosition_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , orientation(0.0)
    , priority_score(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _orientation_type;
  _orientation_type orientation;

   typedef double _priority_score_type;
  _priority_score_type priority_score;





  typedef boost::shared_ptr< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> const> ConstPtr;

}; // struct OptimalPosition_

typedef ::human_clustering_pipeline::OptimalPosition_<std::allocator<void> > OptimalPosition;

typedef boost::shared_ptr< ::human_clustering_pipeline::OptimalPosition > OptimalPositionPtr;
typedef boost::shared_ptr< ::human_clustering_pipeline::OptimalPosition const> OptimalPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator1> & lhs, const ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.orientation == rhs.orientation &&
    lhs.priority_score == rhs.priority_score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator1> & lhs, const ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace human_clustering_pipeline

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dfd8a1c68c8f6ee8f557969f62c7f98";
  }

  static const char* value(const ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dfd8a1c68c8f6eeULL;
  static const uint64_t static_value2 = 0x8f557969f62c7f98ULL;
};

template<class ContainerAllocator>
struct DataType< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_clustering_pipeline/OptimalPosition";
  }

  static const char* value(const ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 orientation\n"
"float64 priority_score\n"
;
  }

  static const char* value(const ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.orientation);
      stream.next(m.priority_score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OptimalPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_clustering_pipeline::OptimalPosition_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "orientation: ";
    Printer<double>::stream(s, indent + "  ", v.orientation);
    s << indent << "priority_score: ";
    Printer<double>::stream(s, indent + "  ", v.priority_score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_CLUSTERING_PIPELINE_MESSAGE_OPTIMALPOSITION_H
