<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>manriix_navigation</name>
  <version>1.0.0</version>
  <description>Navigation package for Manriix robot with Nav2 integration</description>
  <maintainer email="hype@todo.todo">hype</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>nav2_bringup</depend>
  <depend>nav2_common</depend>
  <depend>nav2_msgs</depend>
  <depend>slam_toolbox</depend>
  <depend>geometry_msgs</depend>
  <depend>tf_transformations</depend>
 
  <!-- Cliff detector dependencies -->
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>


  <exec_depend>manriix_perception</exec_depend>
  <exec_depend>python3-transforms3d</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <!-- Route server for graph-based navigation -->  
  <exec_depend>nav2_route</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>